--- #YAML:1.0
name:                App-Widget
version:             0.966
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Data::Inheritable:      0
    Compress::Zlib:                0
    Data::Dumper:                  0
    Date::Format:                  0
    Date::Parse:                   0
    Devel::StackTrace:             0
    Exception::Class:              0
    MIME::Base64:                  2.1
    Storable:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
