# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         App-Widget
version:      0.962
version_from: 
installdirs:  site
requires:
    Class::Data::Inheritable:      0
    Compress::Zlib:                0
    Data::Dumper:                  0
    Date::Format:                  0
    Date::Parse:                   0
    Devel::StackTrace:             0
    Exception::Class:              0
    MIME::Base64:                  2.1
    Storable:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
