--- #YAML:1.0
name:               App-Widget
version:            0.968
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Data::Inheritable:  0
    Compress::Zlib:       0
    Data::Dumper:         0
    Date::Format:         0
    Date::Parse:          0
    Devel::StackTrace:    0
    Exception::Class:     0
    MIME::Base64:         2.1
    Storable:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
